"""The routing tables in the docs must match what the registry answers.

``docs/content/kernels/softmax.md`` says its routing is "generated by probing
the kernels" -- but the fences are checked-in text, and checked-in text is a
second copy of the routing rules. The second copy is the one that goes stale;
that is the exact failure the kernel registry exists to remove (an error
message advised "use softmax_columns for width >= 128" long after the boundary
had moved to 65).

So this test reads the documented tables back and probes the registry at every
boundary they claim. A kernel whose domain moves without the docs following
fails here.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from ipu_apps.kernel_registry import resolve

# Runfiles and a plain checkout put the docs in the same place relative to the
# repo root, so walk up until it appears.
_DOC = None
for _parent in Path(__file__).resolve().parents:
    _candidate = _parent / "docs/content/kernels/softmax.md"
    if _candidate.exists():
        _DOC = _candidate
        break

# `n 1..127   softmax_rows_partial`, `n = 128  softmax_rows`, `n 129..  <name>`
_ROW = re.compile(
    r"^(?P<param>n|width)\s+(?:=\s*(?P<exact>\d+)|(?P<start>\d+)\.\.(?P<end>\d+)?)"
    r"\s+(?P<kernel>\w+)\s*$"
)

# Which query each documented parameter describes: (dim, shape from the value).
_AXIS = {
    "n": (1, lambda v: (8, v)),
    "width": (0, lambda v: (8, v)),
}

# How far past an open-ended run ("n 129..") to probe. Any value well beyond
# the last boundary exercises the same claim.
_OPEN_ENDED_PROBE = 512


def _documented_runs() -> list[tuple[str, int, int | None, str]]:
    runs = []
    # Fences carry an optional info string (```python), so match that too --
    # pairing a closing fence with the next opening one finds nothing.
    fences = re.findall(r"^```[^\n]*\n(.*?)^```", _DOC.read_text(), re.S | re.M)
    for block in fences:
        for line in block.splitlines():
            match = _ROW.match(line.strip())
            if not match:
                continue
            param, kernel = match["param"], match["kernel"]
            if match["exact"]:
                value = int(match["exact"])
                runs.append((param, value, value, kernel))
            else:
                end = int(match["end"]) if match["end"] else None
                runs.append((param, int(match["start"]), end, kernel))
    return runs


pytestmark = pytest.mark.skipif(
    _DOC is None, reason="docs/content/kernels/softmax.md is not in the runfiles"
)


def test_the_doc_actually_contains_routing_tables():
    """Guards the parser: a doc rewrite that drops the fences must not turn
    this file into a test that silently checks nothing."""
    runs = _documented_runs()
    assert len(runs) >= 5, f"parsed only {len(runs)} documented runs from {_DOC}"
    assert {param for param, *_ in runs} == {"n", "width"}


@pytest.mark.parametrize("param,start,end,kernel", _documented_runs() if _DOC else [])
def test_documented_routing_matches_the_registry(param, start, end, kernel):
    dim, build = _AXIS[param]
    probes = {start, end if end is not None else _OPEN_ENDED_PROBE}
    for value in probes:
        verdict = resolve("softmax", shape=build(value), dim=dim)
        assert verdict.supported, f"{param}={value}: {verdict.reason}"
        assert verdict.app_name == kernel, (
            f"docs say {param}={value} routes to {kernel}, registry answers "
            f"{verdict.app_name}. Re-probe the table in {_DOC.name}."
        )


@pytest.mark.parametrize("param,start,end,kernel", _documented_runs() if _DOC else [])
def test_documented_boundaries_are_real_boundaries(param, start, end, kernel):
    """A run that claims to start at ``start`` must actually change hands
    there -- otherwise the table describes a boundary the kernels do not have."""
    if start == 1:
        return  # nothing below it to differ from
    dim, build = _AXIS[param]
    below = resolve("softmax", shape=build(start - 1), dim=dim)
    assert below.app_name != kernel, (
        f"docs start a {kernel} run at {param}={start}, but {param}={start - 1} "
        f"routes there too, so the documented boundary is not where it says."
    )
